import { ThemeProvider, createTheme } from "@mui/material";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Dashboard from "~/components/Dashboard";

const defaultTheme = createTheme();

export default function Layout({ children }: { children: React.ReactNode }) {
  const { data } = useSession();
  return (
    <ThemeProvider theme={defaultTheme}>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard>
        <main>{children}</main>
      </Dashboard>
    </ThemeProvider>
  );
}
